name: Node.js Package
# 监测图床分支，2020年10月后github新建仓库默认分支改为main，记得更改
on:
  push:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "22.14"
          registry-url: https://registry.npmjs.org/

      - run: npm install

      - run: git config user.name "github-actions[bot]"
      - run: git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      
      - run: npm version patch
      - run: git push origin HEAD --follow-tags

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
